Some fixes to work
paulbovbel/zbar_ros pull request #2
Opened 2017-07-14 06:31 UTC by furushchev

- requires mono8 image as zbar::Image
- fix memory leak

2017-07-14 15:26 UTC, paulbovbel requested changes
The image encoding should probably be a rosparam rather than a fixed string. If you'd like the default to be something other than mono8, happy to change it given some rationale.

2017-07-14 16:06 UTC, furushchev commented
@paulbovbel Thanks for reviewing!
Well, it's ok to support rosparam to change destination encoding, but `zbar::Image` with parameter `Y800` only supports `mono8`.
If any images whose encoding is NOT `mono8` are given to `zbar::Image`, ImageScanner returns nothing (even no error shows up..)

2017-07-14 16:17 UTC, paulbovbel commented
Ah, good call, just looked up what Y800 is. I've seen this configuration work, but it's possible suboptimal.

2017-07-14 16:17 UTC, paulbovbel approved these changes

2017-07-18 00:24 UTC, furushchev commented
@paulbovbel Thanks for approve. Any other place to be fixed?

2017-08-11 12:32 UTC, furushchev commented
kindly ping to maintainer

2017-08-11 15:03 UTC, mikepurvis commented
Looks good, thanks!

2017-08-11 15:03 UTC, merged